// <auto-generated />
namespace Tarea2p2.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class SegundaCreada : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(SegundaCreada));
        
        string IMigrationMetadata.Id
        {
            get { return "202504062224012_SegundaCreada"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
